### ISSUE TITLE
[Bug] Kessel

### ISSUE THREAD

**Issue by Bubbelwubbel** [note3crafter/Core-V5#17]
Wenn ich einen Kessel setze, kommt diese Fehler meldung:
![image](https://user-images.githubusercontent.com/65186341/116046588-82bff480-a673-11eb-8cad-0896b6698655.png)

**Comment by note3crafter** [comment]
Schaue ich mir heute Abend an :)

**Comment by note3crafter** [comment]
Bug wurde behoben!
