### ISSUE TITLE
Bug REPORT

### ISSUE THREAD

**Issue by Bubbelwubbel** [note3crafter/Core-V5#3]
Ich möchte einen Bug Report:
![image](https://user-images.githubusercontent.com/65186341/112056714-a1087100-8b58-11eb-9905-03f4a4ce2f39.png)
Bitte fixt es, der Command ist dafür /ban.

Mit Sehr Freundlichen Mega Grüßen FlxiBoy

**Comment by note3crafter** [comment]
Fehler ist Beseitigt...
