### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by Bubbelwubbel** [note3crafter/Core-V5#4]
Idee für Core V6 lol
/invsee, /ecinvsee und im Gamemode 3 Kisten Öffnen jedoch mit keiner Öffnungs Animation :)

**Comment by note3crafter** [comment]
Vielleicht... muss erstmal anderes Machen

**Comment by note3crafter** [comment]
invsee sowie enderinvsee sind nun hinzugefügt... kisten im gamemode3 öffnen wird vorsert nicht kommen... wenn du dieses feature dennoch willst kannste gerne es hinzufügen :D
