### ISSUE TITLE
Kurze doofe frage zu denn Schildern

### ISSUE THREAD

**Issue by ghost** [note3crafter/Core-V5#5]
Die Schilder werden wahrscheinlich nur auf Altay funktionieren? Wenn ich es nun für pmmp einsetzen werde dann würde 255 BlockFactory kacke mich nerven oder als ich es gemacht habe konnte ich die Schilder platzieren die Texturen werden zu normalen schild gewechselt

Ist das ein Codefehler oder liegt es an der fehlenden api4 von pmmp

**Comment by ghost** [comment]
Plus issue #2

Bitte ändere in dem Ordner Arcacia Sign 

Die Block Art du hast Buchstaben ausgelassen

return BlockFactory::get(Block::SIGN_POST);

Statt SIGN_POST hast du... SIG geschrieben :)

**Comment by note3crafter** [comment]
die werden zu den Normalen Gewechselt auch bei Altay so sind sie wenigstens nutzbar... ein Upate Kommt gleich so oder so

**Comment by note3crafter** [comment]
Fehler ost auch Behoben
